export const SET_SELECTED_TRACKABLE_LOADING = "SET_SELECTED_TRACKABLE_LOADING";
export const SET_SELECTED_TRACKABLE = "SET_SELECTED_TRACKABLE";
export const CLEAR_SELECTED_TRACKABLE = "CLEAR_SELECTED_TRACKABLE";
