export const SET_TRACKABLE_LIST_LOADING = "SET_TRACKABLE_LIST_LOADING";
export const SET_TRACKABLE_LIST = "SET_TRACKABLE_LIST";
export const CLEAR_TRACKABLE_LIST = "CLEAR_TRACKABLE_LIST";

export const SET_SELECTED_TRACKABLE_LOADING = "SET_SELECTED_TRACKABLE_LOADING";
export const SET_SELECTED_TRACKABLE = "SET_SELECTED_TRACKABLE";
export const CLEAR_SELECTED_TRACKABLE = "CLEAR_SELECTED_TRACKABLE";
