export const SET_SELECTED_QUESTION_LOADING = "SET_SELECTED_QUESTION_LOADING";
export const SET_SELECTED_QUESTION = "SET_SELECTED_QUESTION";
export const CLEAR_SELECTED_QUESTION = "CLEAR_SELECTED_QUESTION";
